# 450+ Practice Questions That Will Make You a Pandas, NumPy, and SQL Pro!

Author: Avi Chawla

LinkedIn: https://www.linkedin.com/in/avi-chawla/

Read my blogs here: https://medium.com/@avi_chawla

## Introduction

This notebook has been created for you to practice three of the most common tools used in building any machine learning or data science applications, i.e., Pandas, NumPy, and SQL!

The practice questions provided will serve as a great resource for those who are looking to familiarize themselves with some of the most common functions used in these tools. 

Appropriate descriptions have been provided for all the questions in this entire exercise which will help you navigate through this exercise easily. If a dataset is to be loaded in the python environment, that has also been provided for you. You can find it on the right panel in the Files section. Do NOT delete any of the files/folders listed there. 

The whole exercise has been divided into nine separate notebooks. Below are the links to all the other notebooks for you to jump from one notebook to another:

- **Pandas**

1. Pandas Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-1-d693ac55-6455-40cf-ae34-867c6a02014e/%2Fnotebook.ipynb) 
2. Pandas Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-dataset-7e3b6755-5d4b-464b-9b75-9c84667ae3bd/%2Fnotebook.ipynb) 

3. Pandas Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-Notebook-employee-part-2-adc5a3ee-5f61-4725-8e46-ccb07899acfc/%2Fnotebook.ipynb) 

4. Pandas Notebook 4: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Pandas-after-employee-f84e02a1-fb6a-428e-af90-8dd99855749a/%2Fnotebook.ipynb)

- **NumPy**

1. NumPy Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/Numpy-part-1-9b9979f2-b708-4292-b466-3d0157564c91/%2Fnotebook.ipynb)

2. NumPy Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-2-4456411e-2ddd-426d-8027-4881080027db/%2Fnotebook.ipynb) **(This Notebook)** 
 
3. NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/%2Fnotebook.ipynb)

- **SQL**

1. SQL Notebook 1: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-1-eac9d782-a9b1-4e84-a1f9-af14080a6121/%2Fnotebook.ipynb)

2. SQL Notebook 2: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/SQL-Notebook-2-1914b214-be03-44a1-be63-ad99e98be639/%2Fnotebook.ipynb)

## How to use this notebook?

At the top right corner, you will find a Duplicate button. This will allow you to create a unique notebook for your own practice and write solutions to the question listed in this notebook.  

If you face any issues or have any feedback, feel free to reach out to me (Avi Chawla) either on Linkedin: https://www.linkedin.com/in/avi-chawla/ or write an email to avi@dsscholar[dot]com. 

Let's begin 🚀!

# NumPy Notebook 2

## Mathematical Operations on NumPy Arrays

In [ ]:
import numpy as np
import pandas as pd

### 36. Add two numpy arrays element-wise

In [ ]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = # Your code here
print(np_array)

### 37. Multiple two numpy arrays element-wise

In [ ]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = # Your code here
print(np_array)

### 38. Subtract two numpy arrays element-wise

In [ ]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = # Your code here
print(np_array)

### 39. Divide two numpy arrays element-wise

In [ ]:
a = np.array([[1, 1, 3], [1, 1, 3], [1, 1, 4]])
b = np.array([[1, 2, 3], [1, 2, 3], [2, 3, 4]])

np_array = # Your code here
print(np_array)

### 40-42. Trigonometric functions

### sin(x)

In [ ]:
a = np.array([1,2,3])

np_array = # Your code here
print(np_array)

### cos(x)

In [ ]:
a = np.array([1,2,3])

np_array = # Your code here
print(np_array)

### tan(x)

In [ ]:
a = np.array([1,2,3])

np_array = # Your code here
print(np_array)

### 43. Print the element-wise floor 

In [ ]:
a = np.linspace(1, 2, 5)

np_array = # Your code here
print(np_array)

### 44. Print the element-wise ceil

In [ ]:
a = np.linspace(1, 2, 5)

np_array = # Your code here
print(np_array)

### 45. Print the element-wise nearest integer

In [ ]:
a = np.linspace(1, 2, 5)

np_array = # Your code here
print(np_array)

### 46. Round to given number of decimal places

In [ ]:
a = np.linspace(1, 2, 7)
decimal_places = 2

np_array = # Your code here
print(np_array)

### 47. Calculate the element-wise exponential

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = # Your code here
print(np_array)

### 48. Calculate the element-wise exponential and round to two decimal places

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = # Your code here
print(np_array)

### 49. Calculate the element-wise natural logarithm 

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = # Your code here
print(np_array)

### 50. Calculate the element-wise natural logarithm and round to two decimal places

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = # Your code here
print(np_array)

### 51. Calculate the element-wise logarithm at base 2

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])


np_array = # Your code here
print(np_array)

### 52. Calculate the element-wise logarithm at base 2 and take floor of the result

In [ ]:
a = np.arange(1, 6)
## array([1, 2, 3, 4, 5])

np_array = # Your code here
print(np_array)

### 53. Find the sum of numpy array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = # Your code here
print(sum_of_array)

### 54. Find the row-wise sum of numpy array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = # Your code here
print(sum_of_array)

### 55. Find the column-wise sum of numpy array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

sum_of_array = # Your code here
print(sum_of_array)

### 56. Calculate the product of array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = # Your code here
print(prod_of_array)

### 57. Find the row-wise product of numpy array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = # Your code here
print(prod_of_array)

### 58. Find the column-wise product of numpy array element

In [ ]:
a = np.array([[1, 2], [3, 4]])

prod_of_array = # Your code here
print(prod_of_array)

### 59. Compute the square root of array elements

In [ ]:
a = np.array([[1, 2], [3, 4]])

np_array = # Your code here
print(np_array)

## Matrix and Vector Operations

### 60. Compute the dot product of two NumPy arrays 

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = # Your code here
print(np_array)

### 61. Compute the row-wise dot product of two NumPy arrays 

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = # Your code here
print(np_array)

### 62. Compute the matrix product of two NumPy arrays

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = # Your code here
print(np_array)

### 63. Compute the matrix product of two NumPy arrays using the @ operator

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])

np_array = # Your code here
print(np_array)

### 64. Compute the length of the vector

In [ ]:
a = np.arange(-4, 5)

vec_len = # Your code here
print(vec_len)

### 65. Sort the array inplace row-wise

In [ ]:
a = np.array([[1,4],[3,1]])

np_array = # Your code here
print(np_array)

### 66. Sort the array inplace column-wise

In [ ]:
a = np.array([[1,4],[3,1]])

np_array = # Your code here
print(np_array)

### 67. Sort the flattened array

In [ ]:
a = np.array([[1,4],[3,1]])

np_array = # Your code here
print(np_array)

### 68. Order of Indices in a Sorted NumPy Array

In [ ]:
a = np.array([3, 1, 2])

np_array = # Your code here
print(np_array)

### 69-71. Find the index corresponding to the Maximum Values.

In [ ]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

### -> In a flattened array

In [ ]:
max_index = ## Your code here
print(max_index)

### -> Indices of max along column

In [ ]:
max_index = ## Your code here
print(max_index)

### -> Indices of max along row

In [ ]:
max_index = ## Your code here
print(max_index)

### 72-74. Find the index corresponding to the Minimum Values.

In [ ]:
a = np.array([[15, 13, 10,  1, 18],
              [14, 19, 19, 17,  8]])

### -> In a flattened array

In [ ]:
min_index = ## Your code here
print(min_index)

### -> Indices of min along column

In [ ]:
min_index = ## Your code here
print(min_index)

### -> Indices of min along row

In [ ]:
min_index = ## Your code here
print(min_index)

### 75. Print the indices of non-zero elements

In [ ]:
a = np.array([[3, 0, 0], [0, 4, 0], [5, 6, 0]])

non_zero_ind = ## Your code here
print(non_zero_ind)

### 76. Find the mean of the whole numpy array

In [ ]:
a = np.array([[1, 2], [3, 4]])

mean = ## Your code here
print(mean)

### 77. Find the mean of the numpy array along row-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

mean = ## Your code here
print(mean)

### 78. Find the mean of the numpy array along column-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

mean = ## Your code here
print(mean)

### 79. Find the median of the whole numpy array

In [ ]:
a = np.array([[1, 2], [3, 4]])

median = ## Your code here
print(median)

### 80. Find the median of the numpy array along row-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

median = ## Your code here
print(median)

### 81. Find the median of the numpy array along column-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

median = ## Your code here
print(median)

### 82. Find the std dev of the whole numpy array

In [ ]:
a = np.array([[1, 2], [3, 4]])

std_dev = ## Your code here
print(std_dev)

### 83. Find the std dev of the numpy array along row-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

std_dev = ## Your code here
print(std_dev)

### 84. Find the std dev of the numpy array along column-axis

In [ ]:
a = np.array([[1, 2], [3, 4]])

std_dev = ## Your code here
print(std_dev)

Great job solving this notebook. Go to NumPy Notebook 3: [Link](https://deepnote.com/workspace/avi-chawla-695b-aee6f4ef-2d50-4fb6-9ef2-20ee1022995a/project/NumPy-Notebook-3-e6587114-b580-4249-b599-540de859e603/%2Fnotebook.ipynb)

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4456411e-2ddd-426d-8027-4881080027db' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>