# Numpy

In [59]:
import numpy as np

In [60]:
print(np.__version__)

1.21.5


In [61]:
x = np.array([1,2,3,4])

In [62]:
x

array([1, 2, 3, 4])

In [63]:
y = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])

In [64]:
y.shape()


TypeError: 'tuple' object is not callable

In [ ]:
y

In [ ]:
y.shape


In [ ]:
y.size

In [ ]:
y.itemsize

In [ ]:
y.item(1,0,1)


In [97]:
a = np.arange(12, dtype = 'uint32').reshape(2,2,3)

In [98]:
a

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=uint32)

In [99]:
np.array([1, 2, 3, 4], dtype='S')

array([b'1', b'2', b'3', b'4'], dtype='|S1')

In [ ]:
a.ndim

In [ ]:
np.zeros(20, dtype = 'long').reshape(2,10)

In [ ]:
arr = np.array([1,2,3,4,5], ndmin = 5)

In [ ]:
arr

In [ ]:
y

In [ ]:
y[0,0,0]

In [ ]:
y

In [ ]:
x = np.array([1,2,3,4])

In [ ]:
x[0:]

In [ ]:
x[:3]

In [ ]:
y

In [65]:
y[0, :, :]

array([[1, 2],
       [3, 4]])

In [72]:
 y = np.array(['ishaq', 'bashaa'])

In [68]:
y.dtype


dtype('<U5')

In [69]:
class(y)

SyntaxError: invalid syntax (674161757.py, line 1)

In [70]:
type(y)

numpy.ndarray

In [73]:
y.dtype

dtype('<U6')

In [100]:
a = [1,2,3]

In [101]:
b = a

In [111]:
id(a)
id(b)


5481199232

In [103]:
a.pop()

3

In [104]:
a

[1, 2]

In [105]:
b

[1, 2]

In [106]:
b.pop()

2

In [107]:
a

[1]

In [129]:
a = [1,2,3]


In [130]:
b = a[:]

In [131]:
b

[1, 2, 3]

In [132]:
a.pop()

3

In [133]:
b

[1, 2, 3]

In [134]:
a

[1, 2]

In [135]:
a.pop()

2

In [136]:
b

[1, 2, 3]

In [137]:
b.pop()

3

In [138]:
b

[1, 2]

In [139]:
a

[1]

In [140]:
x = [1,2,3]

In [141]:
y = x

In [142]:
x[0] = 2

In [143]:
x

[2, 2, 3]

In [144]:
y

[2, 2, 3]

In [145]:
x = 'ishaq'

In [146]:
y = x

In [147]:
x[0] = 'a'

TypeError: 'str' object does not support item assignment

In [148]:
x[0]

'i'

In [149]:
x = 'Ishaq'

In [150]:
y = x

In [151]:
x = x + 'basha'

In [152]:
x

'Ishaqbasha'

In [153]:
y

'Ishaq'

In [164]:
x = {'Name' : [1,2,3]}

In [165]:
x

{'Name': [1, 2, 3]}

In [166]:
y = x

In [162]:
x['Name']


[1, 2, 3]

In [163]:
del x, y

In [167]:
x['state'] = [1,2]

In [168]:
y

{'Name': [1, 2, 3], 'state': [1, 2]}

In [182]:
x = (1,2,3)

In [170]:
type(x)

tuple

In [171]:
x = {'ishaq', 'basha', 'ishaq'}

In [172]:
x

{'basha', 'ishaq'}

In [173]:
x.add('bad')

In [174]:
x

{'bad', 'basha', 'ishaq'}

In [175]:
y = x

In [176]:
x.add('share')

In [177]:
y

{'bad', 'basha', 'ishaq', 'share'}

In [180]:
y = x.copy()


In [181]:
y

{'bad', 'basha', 'ishaq', 'share'}

In [183]:
x

(1, 2, 3)

In [184]:
y = x

In [185]:
id(y)

5478416704

In [186]:
id(x)

5478416704

In [201]:
a = np.array([1,2,3])

In [202]:
id(a)


5479944336

In [203]:
b = a.view()

In [197]:
id(b)

5479869968

In [204]:
a[0] = 20

In [205]:
a

array([20,  2,  3])

In [206]:
b

array([20,  2,  3])

In [228]:
a = [1,2,3]

In [208]:
b= a

In [209]:
a[0]  = 10

In [210]:
b

[10, 2, 3]

In [213]:
a[0] = a[0]+2

In [214]:
a

[12, 2, 3]

In [215]:
b

[12, 2, 3]

In [227]:
a

[12, 2, 3, 10, 12, 2, 3, 10]

In [217]:
b

[12, 2, 3]

In [218]:
id(a)

5479863104

In [219]:
id(b)

5479863104

In [220]:
a.append(10)

In [221]:
a

[12, 2, 3, 10]

In [222]:
b

[12, 2, 3, 10]

In [223]:
a = a+a

In [224]:
a

[12, 2, 3, 10, 12, 2, 3, 10]

In [225]:
b

[12, 2, 3, 10]

In [226]:
id(a)

5480109696

In [229]:
a

[1, 2, 3]

In [230]:
id(a)

5482152832

In [231]:
a = a+a

In [232]:
id(a)

5482269440

In [234]:
x = np.array([1,2,3])

In [235]:
id(x)

5479945296

In [239]:
x.itemset(1)

ValueError: can only convert an array of size 1 to a Python scalar

In [248]:
x = np.array([1,2,3])

In [249]:
y = x
z = x.view()
print(id(x))
print(id(y))
print(id(z))

5479084752
5479084752
5482847856


In [250]:
x[0] = 12

In [251]:
print(id(x))
print(id(y))
print(id(z))

5479084752
5479084752
5482847856


In [252]:
x

array([12,  2,  3])

In [253]:
y

array([12,  2,  3])

In [254]:
z

array([12,  2,  3])

In [255]:
z[0] = 3

In [262]:
print(x)
print(y)
print(z)

[2 2 3]
[2 2 3]
[2 2 3]


In [263]:
print(id(x))
print(id(y))
print(id(z))

5479084752
5479084752
5482847856


In [261]:
y[0] = 2